/- Copyright (c) Heather Macbeth, 2022.  All rights reserved. -/
import Library.Basic
import Library.Theory.ModEq.Defs

math2001_init


/- Note.  The disguise is two layers deep this time.  `a ≡ b [ZMOD n]` is defined as `n ∣ a - b`,
and `∣` is itself the existential from Section 3.2, so underneath everything

    a ≡ b [ZMOD n]   means   ∃ k, a - b = n * k

That is why `use` proves a congruence and `obtain` takes one apart, with no mention of either `∣`
or `ModEq` in between.  Lean unfolds both layers without being asked.

Saying so matters more here than it did for `∣`.  Congruence is one relation, but there are
several equivalent ways to picture it, and which one you carry around depends on how much algebra
you have met.  "Same remainder on division by `n`" is one.  "Same class in ℤ/nℤ" is another, and
"the difference lies in the ideal generated by `n`" another again.  Lean still has to pick one to
compute with, and it picks `n ∣ a - b`.  The `show` before each `use`, and the annotation on each
`obtain`, are what say which picture is on screen.

Every proof in this section is the same three steps.  Subtract the two sides.  Factor out the
difference the hypothesis gives you.  Read the remaining factor off as the witness.

The `show` goes before the `use` rather than after it.  Before, it states the existential you are
about to satisfy, which is the thing the notation was hiding.  After, it would only restate the
equation that the `calc` beneath it already opens and closes with. -/


example : 11 ≡ 3 [ZMOD 4] := by
  show ∃ k, (11:ℤ) - 3 = 4 * k
  use 2
  numbers

example : -5 ≡ 1 [ZMOD 3] := by
  show ∃ k, (-5:ℤ) - 1 = 3 * k
  use -2
  numbers

theorem Int.ModEq.add {n a b c d : ℤ} (h1 : a ≡ b [ZMOD n]) (h2 : c ≡ d [ZMOD n]) :
    a + c ≡ b + d [ZMOD n] := by
  dsimp [Int.ModEq] at *
  obtain ⟨x, hx : a - b = n * x⟩ := h1
  obtain ⟨y, hy : c - d = n * y⟩ := h2
  show ∃ k, a + c - (b + d) = n * k
  use x + y
  calc
    a + c - (b + d) = a - b + (c - d) := by ring
    _ = n * x + n * y := by rw [hx, hy]
    _ = n * (x + y) := by ring


theorem Int.ModEq.sub {n a b c d : ℤ} (h1 : a ≡ b [ZMOD n]) (h2 : c ≡ d [ZMOD n]) :
    a - c ≡ b - d [ZMOD n] := by
  obtain ⟨x, hx : a - b = n * x⟩ := h1
  obtain ⟨y, hy : c - d = n * y⟩ := h2
  show ∃ k, a - c - (b - d) = n * k
  use x - y
  calc
    a - c - (b - d) = a - b - (c - d) := by ring
    _ = n * x - n * y := by rw [hx, hy]
    _ = n * (x - y) := by ring

theorem Int.ModEq.neg {n a b : ℤ} (h1 : a ≡ b [ZMOD n]) : -a ≡ -b [ZMOD n] := by
  obtain ⟨x, hx : a - b = n * x⟩ := h1
  show ∃ k, -a - -b = n * k
  use -x
  calc
    -a - -b = -(a - b) := by ring
    _ = -(n * x) := by rw [hx]
    _ = n * -x := by ring

theorem Int.ModEq.mul {n a b c d : ℤ} (h1 : a ≡ b [ZMOD n]) (h2 : c ≡ d [ZMOD n]) :
    a * c ≡ b * d [ZMOD n] := by
  obtain ⟨x, hx : a - b = n * x⟩ := h1
  obtain ⟨y, hy : c - d = n * y⟩ := h2
  show ∃ k, a * c - b * d = n * k
  use x * c + b * y
  calc
    a * c - b * d = (a - b) * c + b * (c - d) := by ring
    _ = n * x * c + b * (n * y) := by rw [hx, hy]
    _ = n * (x * c + b * y) := by ring


theorem Int.ModEq.pow_two (h : a ≡ b [ZMOD n]) : a ^ 2 ≡ b ^ 2 [ZMOD n] := by
  obtain ⟨x, hx : a - b = n * x⟩ := h
  show ∃ k, a ^ 2 - b ^ 2 = n * k
  use x * (a + b)
  calc
    a ^ 2 - b ^ 2 = (a - b) * (a + b) := by ring
    _ = n * x * (a + b) := by rw [hx]
    _ = n * (x * (a + b)) := by ring


theorem Int.ModEq.pow_three (h : a ≡ b [ZMOD n]) : a ^ 3 ≡ b ^ 3 [ZMOD n] := by
  obtain ⟨x, hx : a - b = n * x⟩ := h
  show ∃ k, a ^ 3 - b ^ 3 = n * k
  use x * (a ^ 2 + a * b + b ^ 2)
  calc
    a ^ 3 - b ^ 3 = (a - b) * (a ^ 2 + a * b + b ^ 2) := by ring
    _ = n * x * (a ^ 2 + a * b + b ^ 2) := by rw [hx]
    _ = n * (x * (a ^ 2 + a * b + b ^ 2)) := by ring

theorem Int.ModEq.pow (k : ℕ) (h : a ≡ b [ZMOD n]) : a ^ k ≡ b ^ k [ZMOD n] :=
  sorry -- we'll prove this later in the book


theorem Int.ModEq.refl (a : ℤ) : a ≡ a [ZMOD n] := by
  show ∃ k, a - a = n * k
  use 0
  ring


example {a b : ℤ} (ha : a ≡ 2 [ZMOD 4]) :
    a * b ^ 2 + a ^ 2 * b + 3 * a ≡ 2 * b ^ 2 + 2 ^ 2 * b + 3 * 2 [ZMOD 4] := by
  obtain ⟨x, hx : a - 2 = 4 * x⟩ := ha
  show ∃ k, a * b ^ 2 + a ^ 2 * b + 3 * a - (2 * b ^ 2 + 2 ^ 2 * b + 3 * 2) = 4 * k
  use x * (b ^ 2 + a * b + 2 * b + 3)
  calc
    a * b ^ 2 + a ^ 2 * b + 3 * a - (2 * b ^ 2 + 2 ^ 2 * b + 3 * 2) =
        (a - 2) * (b ^ 2 + a * b + 2 * b + 3) :=
      by ring
    _ = 4 * x * (b ^ 2 + a * b + 2 * b + 3) := by rw [hx]
    _ = 4 * (x * (b ^ 2 + a * b + 2 * b + 3)) := by ring


/- Note.  The same statement as above, proved without ever unfolding the definition.  Each lemma
from this section reduces a congruence between compound expressions to congruences between their
parts, and `Int.ModEq.refl` finishes the parts that are literally equal.  That is what those
lemmas were for.

`add` and `mul` each leave two goals, so this proof is a tree four levels deep rather than a list
of steps, and the bullets are what make that visible.  Flattened into a single run of twelve
`apply` calls it compiles just as well, but then working out which goal any given line addresses
means simulating every branch above it. -/

example {a b : ℤ} (ha : a ≡ 2 [ZMOD 4]) :
    a * b ^ 2 + a ^ 2 * b + 3 * a ≡ 2 * b ^ 2 + 2 ^ 2 * b + 3 * 2 [ZMOD 4] := by
  apply Int.ModEq.add
  · apply Int.ModEq.add
    · apply Int.ModEq.mul
      · apply ha
      · apply Int.ModEq.refl
    · apply Int.ModEq.mul
      · apply Int.ModEq.pow
        apply ha
      · apply Int.ModEq.refl
  · apply Int.ModEq.mul
    · apply Int.ModEq.refl
    · apply ha

/-! # Exercises -/


example : 34 ≡ 104 [ZMOD 5] := by
  show ∃ k, (34:ℤ) - 104 = 5 * k
  use -14
  numbers

theorem Int.ModEq.symm (h : a ≡ b [ZMOD n]) : b ≡ a [ZMOD n] := by
  obtain ⟨x, hx : a - b = n * x⟩ := h
  show ∃ k, b - a = n * k
  use -x
  calc
    b - a = -(a - b) := by ring
    _ = -(n * x) := by rw [hx]
    _ = n * -x := by ring

theorem Int.ModEq.trans (h1 : a ≡ b [ZMOD n]) (h2 : b ≡ c [ZMOD n]) :
    a ≡ c [ZMOD n] := by
  obtain ⟨x, hx : a - b = n * x⟩ := h1
  obtain ⟨y, hy : b - c = n * y⟩ := h2
  show ∃ k, a - c = n * k
  use x + y
  calc
    a - c = a - b + (b - c) := by ring
    _ = n * x + n * y := by rw [hx, hy]
    _ = n * (x + y) := by ring

example : a + n * c ≡ a [ZMOD n] := by
  show ∃ k, a + n * c - a = n * k
  use c
  ring


example {a b : ℤ} (h : a ≡ b [ZMOD 5]) : 2 * a + 3 ≡ 2 * b + 3 [ZMOD 5] := by
  obtain ⟨x, hx : a - b = 5 * x⟩ := h
  show ∃ k, 2 * a + 3 - (2 * b + 3) = 5 * k
  use 2 * x
  calc
    2 * a + 3 - (2 * b + 3) = 2 * (a - b) := by ring
    _ = 2 * (5 * x) := by rw [hx]
    _ = 5 * (2 * x) := by ring

example {m n : ℤ} (h : m ≡ n [ZMOD 4]) : 3 * m - 1 ≡ 3 * n - 1 [ZMOD 4] := by
  obtain ⟨x, hx : m - n = 4 * x⟩ := h
  show ∃ k, 3 * m - 1 - (3 * n - 1) = 4 * k
  use 3 * x
  calc
    3 * m - 1 - (3 * n - 1) = 3 * (m - n) := by ring
    _ = 3 * (4 * x) := by rw [hx]
    _ = 4 * (3 * x) := by ring

example {k : ℤ} (hb : k ≡ 3 [ZMOD 5]) :
    4 * k + k ^ 3 + 3 ≡ 4 * 3 + 3 ^ 3 + 3 [ZMOD 5] := by
  obtain ⟨x, hx : k - 3 = 5 * x⟩ := hb
  show ∃ m, 4 * k + k ^ 3 + 3 - (4 * 3 + 3 ^ 3 + 3) = 5 * m
  use x * (k ^ 2 + 3 * k + 13)
  calc
    4 * k + k ^ 3 + 3 - (4 * 3 + 3 ^ 3 + 3) = (k - 3) * (k ^ 2 + 3 * k + 13) := by ring
    _ = 5 * x * (k ^ 2 + 3 * k + 13) := by rw [hx]
    _ = 5 * (x * (k ^ 2 + 3 * k + 13)) := by ring
